name: ai-robo-advisor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - pip=25.1
  - numpy=2.3.0
  - pandas=2.3.0
  - scikit-learn=1.6.1
  - matplotlib=3.10.3
  - plotly=6.1.2
  - streamlit=1.46.0
  - yfinance=0.2.28
  - joblib=1.4.2
  - requests=2.32.4
  - pip:
    - torch==2.7.0 --index-url https://download.pytorch.org/whl/cu126
    - torchvision --index-url https://download.pytorch.org/whl/cu126
    - torchaudio --index-url https://download.pytorch.org/whl/cu126
    - tabpfn
    - psutil